### ISSUE TITLE
Implement deploy

### ISSUE THREAD

**Issue by nijikokun** [Kong/kong-portal-cli#1]
Command:

```
portal deploy <workspace>
```

Options:

- `-u,--upstream`: string
- `-t,--token`: string
- `--watch`

Features:

- [ ] Wipe upstream contents
- [x] Upload local contents
- [x] Watch local contents and deploy on change

**Comment by konwrz20** [comment]
Hi, do you know when deploy function will be ready for use? If not, could you tell me if kong's developer portal editor is only place where I can edit kong's UI files?
