### ISSUE TITLE
Deploy function doesn't work on Windows

### ISSUE THREAD

**Issue by konwrz20** [Kong/kong-portal-cli#11]
Hi, 
I've tested your tool on linux and it works perfectly, but when I'm trying to use it on Windows, deploy function doesn't work. Is there any chance, it would work on Windows? :)

**Comment by HenriPro** [comment]
Hey thanks for filing an issue, can you provide some more information. What version of kong are using and what version of windows are using? 

This tool is intended for use for kong 1.3 EE.

**Comment by konwrz20** [comment]
I'm using:
- kong-portal-cli v1.0.0
- kong from image `kong-enterprise-edition-amqp-enhanced:1.3-rc1-alpine`
- Windows 10
When I'm trying to deploy default developers portal (`portal deploy default`) on Windows I'm getting output: [output.txt](https://github.com/Kong/kong-portal-cli/files/3803514/output.txt)
Exit code of this operation is 0.

When I'm using WSL everything works correctly :)

**Comment by Jlawlzz** [comment]
@konwrz20 

Thanks for the followup!  We will look into the issue and will link the PR fix to this ticket once submitted.

**Comment by Jlawlzz** [comment]
https://github.com/Kong/kong-portal-cli/pull/14

**Comment by Jlawlzz** [comment]
#14 PR merged, closing isssue.
