### ISSUE TITLE
Deploy function doesn't remove locally removed files

### ISSUE THREAD

**Issue by konwrz20** [Kong/kong-portal-cli#12]
Hi,
I'm using:
- kong-portal-cli v1.0.0
- kong from image kong-enterprise-edition-amqp-enhanced:1.3-rc1-alpine

Is there a chance, that `deploy` and `deploy --watch` functions will also remove locally removed files? because calling `wipe` and than `deploy` functions every time you change file name or remove unnecessary file is not very comfortable.

**Comment by Jlawlzz** [comment]
Hi @konwrz20,

Thank you for the ticket, this is a known issue and something we are planning on fixing soon.  Running `wipe` and then `deploy` is certainly frustrating.  Will update this ticket with the PR fix once submitted!

**Comment by HenriPro** [comment]
PR merged https://github.com/Kong/kong-portal-cli/pull/21, closing issue
