### ISSUE TITLE
Deploy function configuration

### ISSUE THREAD

**Issue by konwrz20** [Kong/kong-portal-cli#13]
Hi,
I'm using:
- kong-portal-cli v1.0.0
- kong from image kong-enterprise-edition-amqp-enhanced:1.3-rc1-alpine

Is there any chance to add optional arguments to `deploy` function, to configure where we want to deploy our code?
Example: `portal deploy WORKSPACE_NAME --name WORKSPACE_NAME --upstream http://UPSTREAM --rbac_token RBAC_TOKEN`

**Comment by Jlawlzz** [comment]
Hi @konwrz20,

Configuration for the CLI can currently be done via [`cli.conf.yaml`](https://github.com/Kong/kong-portal-templates/blob/dev-master/workspaces/default/cli.conf.yaml) file within the `kong-portal-templates` repository (`dev-master` branch).  If optional command line args that override the `cli.con.yaml` configuration would be helpful, we can certainly add the feature to our roadmap to support in the future.

**Comment by konwrz20** [comment]
Yes, it will be really helpful for CI/CD scripts. Thank you :)

**Comment by Jlawlzz** [comment]
https://github.com/Kong/kong-portal-cli/pull/15

**Comment by Jlawlzz** [comment]
PR #15 Merged, Closing PR.
