### ISSUE TITLE
Latest release, 3.5.0 , not published

### ISSUE THREAD

**Issue by johanhammar** [Kong/kong-portal-cli#155]
Hi!

It seems the last release, 3.5.0, is not published?

![image](https://user-images.githubusercontent.com/69011/213977318-18d0e801-1c9e-422f-bdbd-9c7002b2555a.png)

![image](https://user-images.githubusercontent.com/69011/213977369-25a5e910-e755-46ad-8b7c-0f1c3a3eef72.png)

**Comment by Mierenga** [comment]
Thanks for pointing out.
3.5.0 was published to NPM but no tag was made: https://www.npmjs.com/package/kong-portal-cli/v/3.5.0

We've also just released 3.6.0 and I've made release tags for both.
