### ISSUE TITLE
Can't deploy .png files with cli command

### ISSUE THREAD

**Issue by Rath-san** [Kong/kong-portal-cli#16]
Hello using:

- kong-portal-cli v1.0.0
- kong from image kong-enterprise-edition-amqp-enhanced:1.3-rc1-alpine

Got an issue with deploying .png files. When using `deploy` command got an http 500 error when kong tries to deploy the .png files. The .svg deploys fine.

**Comment by Jlawlzz** [comment]
Hello @Rath-san, non svg (png/jpg/etc) images should be base-64 encoded before being saved.  The images will be decoded upon retrieval from the server. This is a current limitation with kong-ee that we hope to address in coming releases.
