### ISSUE TITLE
Number of fetched files is below 100; ought add query parameter to get all files from remote repository

### ISSUE THREAD

**Issue by zabrowarnyrafal** [Kong/kong-portal-cli#17]

**Comment by Jlawlzz** [comment]
Hello @zabrowarnyrafal thanks for submitting this ticket!  This is a known issue with the CLI, I will update this ticket with the PR fix once merged.

**Comment by HenriPro** [comment]
PR https://github.com/Kong/kong-portal-cli/pull/21 merged, closing issue
