### ISSUE TITLE
Upload no text files result with exception

### ISSUE THREAD

**Issue by zabrowarnyrafal** [Kong/kong-portal-cli#19]
It would be nice to have possibility to upload png, jpg, ttf wor woff2 files. Now deploy command ends with exception when I try to upload fontawsome fontset

**Comment by HenriPro** [comment]
Hey @zabrowarnyrafal  Thank you for the submitting a issue. 
Easy Image uploading from the the cli is a planned feature. Currently images can be deployed, but only by bas64encoding the image first.

Other non-text files are not currently on the roadmap for the time being.

**Comment by HenriPro** [comment]
PR https://github.com/Kong/kong-portal-cli/pull/23 merged, closing issue.
