### ISSUE TITLE
Unable to install CLI

### ISSUE THREAD

**Issue by bks71** [Kong/kong-portal-cli#28]
Trying to install CLI with `npm install -g kong-portal-cli`

Receive the following error:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/kong-portal-cli/bin/portal.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/kong-portal-cli/bin/portal.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
[2020-01-22T10_59_24_253Z-debug.log](https://github.com/Kong/kong-portal-cli/files/4096736/2020-01-22T10_59_24_253Z-debug.log)

**Comment by HenriPro** [comment]
Thanks for the report, there was an error in publishing, it should be resolved now.
