### ISSUE TITLE
Bypass SSL verification

### ISSUE THREAD

**Issue by tamsler** [Kong/kong-portal-cli#40]
Is there a way to bypass SSL verification when executing portal commands?

> portal fetch default
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',

**Comment by tamsler** [comment]
I think we could have a config file entry that could be read by the RestClient.ts and configure axios to not validate SSL:
https://github.com/axios/axios/issues/535

**Comment by kinman** [comment]
@tamsler can you give the use case for bypassing verification? Are you trying to use a self-signed cert? Or do you want to bypass all validation, to allow invalid and expired certs?

**Comment by HenriPro** [comment]
Implemented with: https://github.com/Kong/kong-portal-cli/pull/43
