### ISSUE TITLE
portal should set a non-zero exit status when it fails

### ISSUE THREAD

**Issue by johanhammar** [Kong/kong-portal-cli#52]
Hi!

When portal fails it should set a non-zero exit code. This would make it easier to handle failures i.e in a CI environment. 

$ portal deploy demo
         ✔ Wiped all Files from demo
Deploying demo:

Deployed ✔ configs
Deploying content ✖ Request failed with status code 400
$ echo $?
0

**Comment by kinman** [comment]
@johanhammar agreed! Would you be willing to submit a PR?

**Comment by johanhammar** [comment]
Hi @kinman. Unfortunately I won't be able to but it is reported as FTI-1972
